AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Entry point that composes networking, IAM, EC2, and RDS nested stacks for the AWS infra demo.

Parameters:
  ProjectName:
    Type: String
    Default: aws-infra-demo
    Description: Short name used for tagging and resource naming.
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, test, prod]
    Description: Environment label added to resource names and tags.
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC.
  PublicSubnetCidr:
    Type: String
    Default: 10.0.0.0/24
    Description: CIDR block for the public subnet.
  PrivateSubnet1Cidr:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR block for the first private subnet.
  PrivateSubnet2Cidr:
    Type: String
    Default: 10.0.2.0/24
    Description: CIDR block for the second private subnet (for RDS subnet group).
  SSHLocation:
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})/(\\d{1,2})"
    Description: The IP address range that can SSH to the EC2 instance.
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t4g.nano
      - t4g.micro
      - t4g.small
      - t4g.medium
    Description: EC2 instance type for the web server.
  EC2KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance.
  DBUsername:
    Type: String
    Default: admin
    MinLength: 1
    MaxLength: 16
    Description: Master username for the RDS instance.
  DBPassword:
    NoEcho: true
    Type: String
    MinLength: 8
    MaxLength: 41
    Description: Master user password for the RDS instance.
  DBAllocatedStorage:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 100
    Description: Allocated storage size (GiB) for the RDS instance.
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t4g.micro
      - db.t4g.small
    Description: Instance class for the RDS instance.
  DBName:
    Type: String
    Default: appdb
    Description: Initial database name to create.
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64
    Description: SSM path for the latest Amazon Linux 2023 AMI.

Resources:
  NetworkingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./networking.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VpcCidr: !Ref VpcCidr
        PublicSubnetCidr: !Ref PublicSubnetCidr
        PrivateSubnet1Cidr: !Ref PrivateSubnet1Cidr
        PrivateSubnet2Cidr: !Ref PrivateSubnet2Cidr
        SSHLocation: !Ref SSHLocation

  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./iam.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  RdsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./rds.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        DBAllocatedStorage: !Ref DBAllocatedStorage
        DBInstanceClass: !Ref DBInstanceClass
        DBName: !Ref DBName
        PrivateSubnet1Id: !GetAtt NetworkingStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt NetworkingStack.Outputs.PrivateSubnet2Id
        RDSSecurityGroupId: !GetAtt NetworkingStack.Outputs.RDSSecurityGroupId

  Ec2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ec2.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        PublicSubnetId: !GetAtt NetworkingStack.Outputs.PublicSubnetId
        EC2SecurityGroupId: !GetAtt NetworkingStack.Outputs.EC2SecurityGroupId
        InstanceType: !Ref InstanceType
        EC2KeyPairName: !Ref EC2KeyPairName
        LatestAmiId: !Ref LatestAmiId
        InstanceProfileName: !GetAtt IamStack.Outputs.InstanceProfileName
        EC2RoleName: !GetAtt IamStack.Outputs.EC2RoleName
        RDSEndpoint: !GetAtt RdsStack.Outputs.RDSEndpoint

Outputs:
  VpcId:
    Description: VPC Id for the demo environment.
    Value: !GetAtt NetworkingStack.Outputs.VpcId
  PublicSubnetId:
    Description: Public subnet where the EC2 instance lives.
    Value: !GetAtt NetworkingStack.Outputs.PublicSubnetId
  InstanceId:
    Description: EC2 instance id.
    Value: !GetAtt Ec2Stack.Outputs.InstanceId
  InstancePublicDNS:
    Description: Public DNS name for the EC2 web server.
    Value: !GetAtt Ec2Stack.Outputs.InstancePublicDNS
  RDSEndpoint:
    Description: RDS endpoint hostname.
    Value: !GetAtt RdsStack.Outputs.RDSEndpoint
  AppBucketName:
    Description: Name of the application S3 bucket.
    Value: !GetAtt Ec2Stack.Outputs.AppBucketName
