AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CI/CD pipeline demo using CodeCommit + CodeBuild + CodePipeline to deploy the infra stack.

Parameters:
  ProjectName:
    Type: String
    Default: aws-infra-demo
    Description: Short name used for tagging and resource naming.
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, test, prod]
    Description: Environment label added to resource names and tags.
  CodeCommitRepositoryName:
    Type: String
    Description: Name of an existing CodeCommit repository that stores the templates.
  CodeCommitBranch:
    Type: String
    Default: main
    Description: Branch CodePipeline should track.
  CloudFormationStackName:
    Type: String
    Default: aws-infra-demo
    Description: Stack name to deploy the infra template to.
  CloudFormationTemplateFile:
    Type: String
    Default: templates/packaged-main.yaml
    Description: Path (in the built artifact) to the infra template file.
  DBPassword:
    NoEcho: true
    Type: String
    MinLength: 8
    MaxLength: 41
    Description: Master user password forwarded to the RDS instance in the infra stack.

Resources:
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-${Environment}-${AWS::AccountId}-${AWS::Region}-pipeline-artifacts
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-pipeline-artifacts

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: codebuild-artifacts
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${PipelineArtifactBucket}
                  - !Sub arn:aws:s3:::${PipelineArtifactBucket}/*
              - Effect: Allow
                Action:
                  - cloudformation:ValidateTemplate
                Resource: "*"
      Path: /
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-codebuild-role

  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: codepipeline-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:UploadArchive
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:CancelUploadArchive
                Resource: !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${CodeCommitRepositoryName}
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:GetBucketVersioning
                Resource:
                  - !Sub arn:aws:s3:::${PipelineArtifactBucket}
                  - !Sub arn:aws:s3:::${PipelineArtifactBucket}/*
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: !GetAtt CodeBuildProject.Arn
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeChangeSet
                Resource: "*"
              - Effect: Allow
                Action: iam:PassRole
                Resource:
                  - !GetAtt CloudFormationDeploymentRole.Arn
                  - !GetAtt CodeBuildServiceRole.Arn
      Path: /
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-codepipeline-role

  CloudFormationDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: cf-execution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:*
                  - rds:*
                  - s3:*
                  - iam:*
                  - logs:*
                  - cloudformation:*
                Resource: "*"
      Path: /
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-cf-role

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-build
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: PACKAGING_BUCKET
            Value: !Ref PipelineArtifactBucket
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-build

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${ProjectName}-${Environment}
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              Configuration:
                RepositoryName: !Ref CodeCommitRepositoryName
                BranchName: !Ref CodeCommitBranch
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployInfra
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Ref CloudFormationStackName
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: !Sub BuildOutput::${CloudFormationTemplateFile}
                RoleArn: !GetAtt CloudFormationDeploymentRole.Arn
                ParameterOverrides: !Sub |
                  {
                    "ProjectName": "${ProjectName}",
                    "Environment": "${Environment}",
                    "DBPassword": "${DBPassword}"
                  }
              RunOrder: 1
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-pipeline

Outputs:
  PipelineName:
    Description: CodePipeline name.
    Value: !Ref Pipeline
  ArtifactBucketName:
    Description: Pipeline artifact bucket.
    Value: !Ref PipelineArtifactBucket
  CodeBuildProjectName:
    Description: CodeBuild project name.
    Value: !Ref CodeBuildProject
